package com.mra.loteriamexicana.utilerias;

import com.mra.loteriamexicana.R;

public class CatalogoCartas {

        public static String[] nombresBaraja = {
                "El Gallo",
                "El Diablito",
                "La Dama",
                "El Catrín",
                "El Paraguas",
                "La Sirena",
                "La Escalera",
                "La Botella",
                "El Barril",
                "El Árbol",
                "El Melón",
                "El Valiente",
                "El Gorrito",
                "La Muerte",
                "La Pera",
                "La Bandera",
                "El Bandonlón",
                "El Violoncello",
                "La Garza",
                "El Pájaro",
                "La Mano",
                "La Bota",
                "La Luna",
                "El Cotorro",
                "El Borracho",
                "El Negrito",
                "El Corazón",
                "La Sandía",
                "El Tambor",
                "El Camarón",
                "Las Jaras",
                "El Músico",
                "La Araña",
                "El Soldado",
                "La Estrella",
                "El Cazo",
                "El Mundo",
                "El Apache",
                "El Nopal",
                "El Alacrán",
                "La Rosa",
                "La Calavera",
                "La Campana",
                "El Cantarito",
                "El Venado",
                "El Sol",
                "La Corona",
                "La Chalupa",
                "El Pino",
                "El Pescado",
                "La Palma",
                "La Maceta",
                "El Arpa",
                "La Rana"
        };

        public static String[] nombresAudioBaraja = {
                "el_gallo",
                "el_diablito",
                "la_dama",
                "el_catrin",
                "el_paraguas",
                "la_sirena",
                "la_escalera",
                "la_botella",
                "el_barril",
                "el_arbol",
                "el_melon",
                "el_valinte",
                "el_gorrito",
                "la_muerte",
                "la_pera",
                "la_bandera",
                "el_bandolon",
                "el_violoncello",
                "la_garza",
                "el_pajaro",
                "la_mano",
                "la_bota",
                "la_luna",
                "el_cotorro",
                "la_borracho",
                "el_negrito",
                "el_corazon",
                "la_sandia",
                "el_tambor",
                "el_camaron",
                "las_jaras",
                "el_musico",
                "la_arania",
                "el_soldado",
                "la_estrella",
                "el_cazo",
                "el_mundo",
                "el_apache",
                "el_nopal",
                "el_alacran",
                "la_rosa",
                "la_calavera",
                "la_campana",
                "el_cantarito",
                "el_venado",
                "el_sol",
                "la_corona",
                "la_chalupa",
                "el_pino",
                "el_pescado",
                "la_palma",
                "la_maceta",
                "al_arpa",
                "la_rana"
        };

    public static String[] nombresAudioVersosBaraja = {
            "el_gallo_verso",
            "el_diablito_verso",
            "la_dama_verso",
            "el_catrin_verso",
            "el_paraguas_verso",
            "la_sirena_verso",
            "la_escalera_verso",
            "la_botella_verso",
            "el_barril_verso",
            "el_arbol_verso",
            "el_melon_verso",
            "el_valinte_verso",
            "el_gorrito_verso",
            "la_muerte_verso",
            "la_pera_verso",
            "la_bandera_verso",
            "el_bandolon_verso",
            "el_violoncello_verso",
            "la_garza_verso",
            "el_pajaro_verso",
            "la_mano_verso",
            "la_bota_verso",
            "la_luna_verso",
            "el_cotorro_verso",
            "la_borracho_verso",
            "el_negrito_verso",
            "el_corazon_verso",
            "la_sandia_verso",
            "el_tambor_verso",
            "el_camaron_verso",
            "las_jaras_verso",
            "el_musico_verso",
            "la_arania_verso",
            "el_soldado_verso",
            "la_estrella_verso",
            "el_cazo_verso",
            "el_mundo_verso",
            "el_apache_verso",
            "el_nopal_verso",
            "el_alacran_verso",
            "la_rosa_verso",
            "la_calavera_verso",
            "la_campana_verso",
            "el_cantarito_verso",
            "el_venado_verso",
            "el_sol_verso",
            "la_corona_verso",
            "la_chalupa_verso",
            "el_pino_verso",
            "el_pescado_verso",
            "la_palma_verso",
            "la_maceta_verso",
            "el_arpa_verso",
            "la_rana_verso"
    };

    public static int idsBaraja [] = {
            R.drawable.el_gallo,
            R.drawable.el_diablito,
            R.drawable.la_dama,
            R.drawable.el_catrin,
            R.drawable.el_paraguas,
            R.drawable.la_sirena,
            R.drawable.la_escalara,
            R.drawable.la_botella,
            R.drawable.el_barril,
            R.drawable.el_arbol,
            R.drawable.el_melon,
            R.drawable.el_valiente,
            R.drawable.el_gorrito,
            R.drawable.la_muerte,
            R.drawable.la_pera,
            R.drawable.la_bandera,
            R.drawable.el_bandolon,
            R.drawable.el_violoncello,
            R.drawable.la_garza,
            R.drawable.el_pajaro,
            R.drawable.la_mano,
            R.drawable.la_bota,
            R.drawable.la_luna,
            R.drawable.el_cotorro,
            R.drawable.el_borracho,
            R.drawable.el_negrito,
            R.drawable.el_corazon,
            R.drawable.la_sandia,
            R.drawable.el_tambor,
            R.drawable.el_camaron,
            R.drawable.las_jaras,
            R.drawable.el_musico,
            R.drawable.la_arania,
            R.drawable.el_soldado,
            R.drawable.la_estrella,
            R.drawable.el_cazo,
            R.drawable.el_mundo,
            R.drawable.el_apache,
            R.drawable.el_nopal,
            R.drawable.el_alacran,
            R.drawable.la_rosa,
            R.drawable.la_calavera,
            R.drawable.la_campana,
            R.drawable.el_cantarito,
            R.drawable.el_venado,
            R.drawable.el_sol,
            R.drawable.la_corona,
            R.drawable.la_chalupa,
            R.drawable.el_pino,
            R.drawable.el_pescado,
            R.drawable.la_palma,
            R.drawable.la_maceta,
            R.drawable.el_arpa,
            R.drawable.la_rana
    };

    public static String[] versosLoteria = {
            "El gallo\n\nEl que le cantó a san Pedro\nno le volverá a cantar.",
            "El diablo\n\nEl diablo son las mujeres\ncuando se quieren casar.",
            "La dama\n\nLa chula de Severiana\nun tacón quería empeñar.",
            "El catrín\n\nDon Ferruco en la Alameda\nsu bastón quería empeñar.",
            "El paraguas\n\nEl paraguas quitasol.",
            "La sirena\n\nMedio cuerpo de sirena,\nmedio cuerpo de mujer.",
            "La escalera\n\nLa escalera, siete palos,\nla escalera del pintor.",
            "La botella\n\nLa botella del tequila,\nla botella del mezcal.",
            "El barril\n\nEl barril es quintaleño,\nel barril del mezcal.",
            "El árbol\n\nEl árbol de la esperanza\nque de venir no se cansa.",
            "El melón\n\nEl melón y sus olores,\nun pedazo me has de dar.",
            "El valiente\n\n’Tate quieto, Valentín,\nno te vayas a pelear.",
            "El gorrito\n\nEl gorrito ponle al nene,\nno se te vaya a resfriar.",
            "La muerte\n\nLa muerte siriquiflaca,\nmontada en su burra flaca.",
            "La pera\n\nMe esperas donde quedamos,\npara poder platicar.",
            "La bandera\n\nBonito cinco de mayo,\nel pabellón nacional.",
            "El bandolón\n\nEl bandolón ya no suena,\nhay que llevarlo a afinar.",
            "El violoncello\n\nEl violoncello del maistro,\nque no deja de sonar.",
            "La garza\n\nLlegaron los picos largos\nde la feria de San Juan.",
            "El pájaro\n\nEl pájaro churlumirlo,\nque no deja de cantar.",
            "La mano\n\nLa mano del escribano,\nla mano del criminal.",
            "La bota\n\nLa bota rechina,\nla bota del general.",
            "La luna\n\nLa luna tuerta de un ojo,\nque no deja de brillar.",
            "El cotorro\n\nPerico, da’cá la pata\ny empiézame a platicar\nlos trabajos que pasabas\ncuando no sabías hablar.",
            "El borracho\n\nAl borracho, mi compañero,\nya se lo van a cargar.",
            "El negrito\n\nPara negros, en La Habana;\nuno acaba de llegar.",
            "El corazón\n\nEl corazón de una ingrata\nyo lo voy a traspasar.",
            "La sandía\n\nLa sandía y su rebanada,\nun pedazo me has de dar.",
            "El tambor\n\nNo te arrugues, cuero viejo,\nque te quiero pa’ tambor.",
            "El camarón\n\nCamarón que se duerme\nse lo lleva la corriente.",
            "Las jaras\n\nLas jaras o no las jaras,\no las dejas de jalar.",
            "El músico\n\nEl músico, trompa de hule.",
            "La araña\n\nLa araña teje su tela.",
            "El soldado\n\nCentinela, ponte alerta,\nque te habla tu general",
            "La estrella\n\nLa estrella polar del norte,\nque no deja de brillar.",
            "El cazo\n\nEl caso que te hago es poco;\nel caso es averiguar.",
            "El mundo\n\nEl mundo es una bola,\ny nosotros, un bolón.",
            "El apache\n\nPara apaches, en Chihuahua;\nuno acaba de llegar.",
            "El nopal\n\nEl auxilio de San Luis,\nque le llaman el nopal.",
            "El alacrán\n\n¡No levantes esa piedra,\nque te pica ese animal!",
            "La rosa\n\nRosa, Rosita, Rosaura,\nRosita se ha de llamar.",
            "La calavera\n\nYa te vide an ca’ la güera.",
            "La campana\n\nLa campana, y tú, debajo.",
            "El cantarito\n\nTodo cabe en un jarrito,\nsabiéndolo acomodar.",
            "El venado\n\nDon Venancio, a la carrera,\nun balazo le han de dar.",
            "El sol\n\nSolito me estoy quedando,\nsolito me he de quedar.",
            "La corona\n\nSi te mueres, te la pongo,\nla coronita imperial.",
            "La chalupa\n\nRema y rema, Joaquinita,\ny no dejes de remar.",
            "El pino\n\nTe empino y me voy de paso,\ny empinado has de quedar.",
            "El pescado\n\nMe pescaron vacilando\nen la puerta del zaguán.",
            "La palma\n\nSube a la palma, palmero,\ny bájame un cocotal.",
            "La maceta\n\nEn la maceta me dieron,\npor no saber barajar.",
            "El arpa\n\nEl arpa vieja de mi suegra.",
            "La rana\n\n¡Qué saltos pega tu hermana\nen la puerta del zaguán!"
    };

}
